config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :clients
  resources :appointments
  get "new_release" => 'appointments#new_release', :as => :new_release
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  validates_presence_of :client
  TYPE = ["Volunteer","Donate Food", "Bulk Donation", "Request a Drop-off"]
  validates :appointment_type, presence: true
  validates :appointment_time, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many  :appointments
  has_many  :messages
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone,  presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10}
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i


  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :client
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with *args, options, &blk
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  layout 'appointment_layout'

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def new_release
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    # @appointment = appointment.find(params[:id])
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      flash.notice = "The appointment record was created successfully."
      redirect_to @appointment
    else
      flash.now.alert = @appointment.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @appointment.update(appointment_params)
      flash.notice = "The appointment record was updated successfully."
      redirect_to @appointment
    else
      flash.now.alert = @appointment.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    # @appointment = appointment.find(params[:id])
    # @appointment.destroy
    # redirect_to @appointment
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def appointment_params
      params.require(:appointment).permit(:appointment_type, :appointment_time, :client_id)
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def catch_not_found(e)
          Rails.logger.debug("We had a not found exception.")
          flash.alert = e.to_s
          redirect_to appointments_path
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  layout 'client_layout'

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash.notice = "The client record was created successfully."
      redirect_to @client
    else
      flash.now.alert = @client.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @client.update(client_params)
      flash.notice = "The client record was updated successfully."
      redirect_to @client
    else
      flash.now.alert = @client.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client data was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to clients_path
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

  respond_to :html, :json

  def index
    @messages = Message.order(created_at: :desc).limit(21)
  end

  def new
    @message = Message.new
    respond_modal_with @message
  end

  def new_message
    @message = Message.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_modal_with @message
  end

  def update
    @message.update(message_params)
    respond_modal_with @message, location: messages_path
  end

  def create
    @message = Message.create(message_params)
    respond_modal_with @message, location: messages_path
  end

  def destroy
    @message.destroy
    redirect_to messages_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/appointments/_form.html.erb
<div class="form">
  <%= form_for(appointment) do |f| %>
    <% if appointment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>
        <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :appointment_type %><br>
      <% Appointment::TYPE.each do |s| %>
        <%= f.radio_button :appointment_type, s %>
        <%= f.label :appointment_type, s, value: s, class: "checkbox-label" %><br>
      <% end %>
    </div>
    <div class="field">
      <%= f.label :appointment_time %>
      <%= f.datetime_select(:appointment_time, order: [:hour, :month, :day, :year], start_year: 2020) %>
    </div>
    <p>
      <strong>Client:</strong>
      <%= f.collection_select :client_id, Client.all, :id, :full_name, include_blank: true %>
    </p>
    <div class="actions">
      <button class="btn btn-primary btn-sm"><%= f.submit %></button>
    </div>
  <% end %>
</div>

app/views/appointments/edit.html.erb
<div class="jumbotron">
  <div class="page">
    <h1>Edit Appointment</h1>
    <p>
    <%= render 'form', appointment: @appointment %>
    </p>
    
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', appointments_path %>
    </button>
  </div>
</div>

app/views/appointments/index.html.erb
<div class="jumbotron">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <h1>Appointments</h1>
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Type</th>
          <th>Time</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td><%= appointment.appointment_type %></td>
            <td><%= appointment.appointment_time %></td>
            <td><%= link_to 'Show', appointment %></td>
            <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
            <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'New appointment', new_appointment_path %>
    </button>
  </div>
</div>

app/views/appointments/new.html.erb
<div class="jumbotron">
  <div class="page">
    <h1>New Appointment</h1>
    <%= render 'form', appointment: @appointment %>
    <br>
    <h6>Don't see your name here? Create a new account!</h6>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'New Account', new_client_path %>
    </button>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', appointments_path %>
    </button>
  </div>
</div>

app/views/appointments/show.html.erb
<div class="jumbotron">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Appointment Type:</strong>
      <%= @appointment.appointment_type %>
    </p>
    <p>
      <strong>Appointment time:</strong>
      <%= @appointment.appointment_time %>
    </p>
    <p>
      <strong>Client:</strong>
      <%= @appointment.client.full_name %>
    </p>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Edit', edit_appointment_path(@appointment) %>
    </button>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', appointments_path %>
    </button>
  </div>
</div>

app/views/clients/_form.html.erb
<div class="form">
<%= form_for(client) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <button class="btn btn-primary btn-sm"><%= f.submit %></button>
  </div>
<% end %>
</div>

app/views/clients/edit.html.erb
<div class="jumbotron">
  <div class="page">
    <h1>Editing Client</h1>
    <p>
    <%= render 'form', client: @client %>
    </p>
    
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', clients_path %>
    </button>
  </div>
</div>

app/views/clients/index.html.erb
<div class="jumbotron">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <h1>Clients</h1>
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Full name</th>
          <th>Phone</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= client.full_name %></td>
            <td><%= client.phone %></td>
            <td><%= client.email %></td>
            <td><%= link_to 'Show', client %></td>
            <td><%= link_to 'Edit', edit_client_path(client) %></td>
            <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'New Client', new_client_path %>
    </button>
  </div>
</div>

app/views/clients/new.html.erb
<div class="jumbotron">
  <div class="page">
    <h1>New User Account</h1>
    <%= render 'form', client: @client %>
    <br>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', clients_path %>
    </button>
  </div>
</div>

app/views/clients/new.js.erb
$("#member").html('<%= j render "clients/_form" %>')

app/views/clients/show.html.erb
<div class="jumbotron">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Full name:</strong>
      <%= @client.full_name %>
    </p>
    <p>
      <strong>Phone:</strong>
      <%= @client.phone %>
    </p>
    <p>
      <strong>Email:</strong>
      <%= @client.email %>
    </p>
    <p>
      <h4>Appointments:</h4>
      <% if @client.appointments.exists? %>
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th>Appointment type</th>
            <th>Appointment time</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <tbody>
          <% @client.appointments.each do |p| %>
            <tr>
              <td><%= p.appointment_type %></td>
              <td><%= p.appointment_time %></td>
              <td><%= link_to 'Show', p %></td>
              <td><%= link_to 'Update', edit_appointment_path(p) %></td>
              <td><%= link_to 'Delete', p, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <p>This client has no appointment.</p>
      <% end %>
      <br>
    </p>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'New appointment', new_appointment_path %>
    </button>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Edit', edit_client_path(@client) %>
    </button>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', clients_path %>
    </button>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to LoveFood.org</h1><br>
    <p>
      We love to share our food with the others,    <br>
      especially those who need it more than us do. <br>
      Help us nourishing people during COVID-19,    <br>
      a little love/food goes a long way.           <br>
    </p><br>
    <div data-content="Bulk Donation? Check *Helper Needed* in the appointment page!"
     data-toggle="popover" title="Popover">
     <%= button_to 'Get involved', appointments_path, :method => :get, :class => "btn btn-primary btn-lg"%>
    </div><br><br>
    <!-- temp use of alert to replace the popover for now -->
    <div class="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      Farmer with overgrown crops?? Have overstocked produce going to waste soon??<br>
      Select Bulk Donation in the appointment page. We'll contact you for more details.
    </div>
    <!-- Popover
    <%#= link_to 'Bulk Donation? Check *Helper Needed* in the appointment page!', new_appointment_path, :remote => true %>

    <%#= link_to 'Add release', new_release_path, :remote => true %>
    <div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          Are you a owner of a farm?<br>
          Have overstocked produce going to waste soon?<br>
          Mark your donate appointment as a bulk donation,<br>
          we'll contact you for details on how can we help to collect them.
        </div>
      </div>
    </div> -->
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <h3>We offer drop-off service</h3>
      <p>For people who couldn't make it to local foodbank and/or drop off locations
        (especially seniors and special need family with kids),
        we help arrange volunteer drop off service.<br>
        Please make an appointment with us and we will contact you for futher details
        about the drop off time and locations.
      </p>
      <button type="button" class="btn btn-outline-primary btn-sm"><%= link_to 'Appointment', new_appointment_path %></button>
    </div>
    <div class="col-lg-6">
      <h3>Help us spread the love</h3>
      <h5>"In times of hardship, collaboration and generosity are key." <br>
        <span class="right">- The Guardian</span>
      </h5><br>
      <p>
        We need your help now more than ever!<br>
        many people are in need of food supply right now due to the coronavirus(COVID-19) pandemic.
      </p>
      <button class="btn btn-outline-primary btn-sm">
        <%= link_to 'Join Us', new_client_path %>
      </button>
      <button type="button" class="btn btn-outline-primary btn-sm">
        <%= link_to 'More Info', 'https://foodbankcenc.org/' %>
      </button>
     </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer bg-black small text-center text-white-50 sticky-bottom">
  <div class="container">Copyright © LoveFood 2020</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#"><img src="/assets/logo1.png" height="70" alt="LoveFood"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><%= link_to 'Home', home_index_path, class: 'navbar-brand' %><span class="sr-only">(current)</span>
      <li class="nav-item"><%= link_to 'Everybody Shares', clients_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Appointment', appointments_path, class: 'nav-link' %></li>
    </ul>
    <button class="btn btn-outline-success my-2 my-sm-0"><%= link_to 'Food Finder', 'https://foodbankcenc.org/food-finder/' %></button>
  </div>
</nav>

app/views/layouts/_new_release.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3 id="myModalLabel">Modal header</h3>
</div>
<div class="modal-body">
  <p>One fine body…</p>
</div>
<div class="modal-footer">
  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
  <button class="btn btn-primary">Save changes</button>
</div>

app/views/layouts/_newmessage.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  *Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "LoveFood" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Share Love & Food" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
    <%= content_for?(:content) ? yield(:content) : yield %>
    </main>
    <div id="modal-holder"></div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/appointment_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <% if !flash[:alert].nil? %>
        <p class="my_alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/client_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Client List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <% if !flash[:alert].nil? %>
        <p class="my_alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/message_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Messages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main role="main">
      <% if !flash[:alert].nil? %>
        <p class="my_alert"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/layouts/new_release.js.erb
$("#myModal").find(".modal-content").html("<%= j (render 'new_release') %>");
$("#myModal").modal('show');

app/views/messages/_form.html.erb
<%= simple_form_for(@message, remote: request.xhr?, html: { data: { modal: true } }) do |f| %>
  <div class="modal-body">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :helper %>
    <%= f.collection_select :client_id, Client.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="modal-footer">
    <%= f.button :submit, class: 'btn-success' %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div class="card border-secondary mb-3">
  <div class="card-header d-flex justify-content-between">
    <%= message.title.truncate(20) %>
    <div class="d-flex justify-content-end">
      <%= link_to 'Edit', edit_message_path(message), class: 'mr-4', data: { modal: true } %>
      <%= link_to message, data: { confirm: 'Are you sure?' }, method: :delete, class: 'text-dark' do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
    </div>
  </div>
  <div class="card-body text-secondary">
    <p class="card-text">
      <%= message.body %>
    </p>
  </div>
</div>

app/views/messages/edit.html.erb
<div class="modal-header">
  <h5 class="modal-title">Edit message</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', message: @message %>

app/views/messages/index.html.erb
<div class="card-columns">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <h1>Messages</h1>
    <p>
      Are you a owner of a farm? Have overstocked crops or veggies going to waste soon?<br>
      Leave a note in the message, we'll send volunteers to help collecting them.
    </p>
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @messages.each do |message| %>
          <tr>
            <td><%= message.title %></td>
            <td><%= message.body %></td>
            <td><%= message.helper %></td>
            <td><%= link_to 'Show', message %></td>
            <td><%= link_to 'Edit', edit_message_path(message) %></td>
            <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'New message', new_message_path %>
    </button>
  </div>
</div>

app/views/messages/new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New message</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<%= render 'form', message: @message %>

app/views/messages/show.html.erb
<div class="jumbotron">
  <div class="page">
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Message Title:</strong>
      <%= @message.message_type %>
    </p>
    <p>
      <strong>Message Body:</strong>
      <%= @message.message_time %>
    </p>
    <p>
      <strong>Client:</strong>
      <%= @message.client.full_name %>
    </p>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Edit', edit_message_path(@message) %>
    </button>
    <button class="btn btn-outline-primary btn-sm">
    <%= link_to 'Back', messages_path %>
    </button>
  </div>
</div>

app/views/messages/view.js.erb
$("#modal-window").find(".modal-content").html("<%= j render 'shared/modal' %>");
$("#modal-window").modal('show');